### ISSUE TITLE
Stitchy on NetBSD

### ISSUE THREAD

**Issue by ghost** [grimace87/Stitchy#1]
FYI, I've packaged Stitchy for NetBSD.
The package is currently in the WIP-repo due to:

1)ongoing pkgsrc freeze ahead of the Q4-release, no new package should be imported right now.

2)lack of a github release-tag, this is needed as we (on NetBSD) don't pull packages from crates.io

http://mail-index.netbsd.org/pkgsrc-wip-changes/2020/12/25/msg018936.html

If, you could provide a github-tag whenever you make a new release in crates.io, I'll be happy to import the package into the main branch once the freeze is over.

**Comment by shining-grimace** [comment]
Apologies for neglecting this issue for so long. I have now pushed a release tag, reflecting the latest release on crates.io (same version as when this issue was created).

**Comment by 0323pin** [comment]
@grimace87 It seems you're working on this project again, awesome 😄 

I had to discard my previous github account but, it was me that oppened this issue.
Just so you know, I still use `stitchy` on a regular basis and I'm happy to see updates to the code.

I did import the package back then, pulling from the latest commit, so it has been available to our users since January 2021.

I'll keep an eye on it, waiting for a new release.

**Comment by shining-grimace** [comment]
@0323pin Glad to hear `stitchy` is useful to you!

I don't work on this project unless I get new ideas, which I'm totally open to. Either way I also still use it regularly myself and will continue to do so.

**Comment by 0323pin** [comment]
@grimace87 Personally, I don't need further features. I'm happy if dependencies are bumped once in a while.

From a package maintainer prespective, it would be nice with a new tag when the above happens, though.

I'm using `stitchy` built from git-HEAD a couple of days ago. All good but, it's a bit weird it's still 0.1.3
