### ISSUE TITLE
Weird layout for 3 images

### ISSUE THREAD

**Issue by gkuznik** [grimace87/Stitchy#4]
Thank you for this library, it's really handy. However I (and my users) noticed a little quirk.
With the default options (grid layout) 2 images result in `1 | 2` and 4 images result in
| 1 | 2 |
|---|---|
| 3 | 4 |

Thus I'd expect 3 images to result in 
| 1 | 2 |
|---|---|
| 3 | |

but it results in `1 | 2 | 3`.
This might have to do with [this code here](https://github.com/grimace87/Stitchy/blob/master/crates/stitchy-core/src/stitch/mod.rs#L161). Why is < 4 considered a special case and could this behaviour be changed?

**Comment by gkuznik** [comment]
This check is probably needed to make the formula later on (`(t - 1)^2 < i`) work, why was this one chosen?
Intutively I'd just use ⌈√n⌉, the square root rounded up as the main axis size

**Comment by shining-grimace** [comment]
Hi @Friendly-Banana, thanks for your feedback!

You're right that this is the result of 3 images being considered a special case. Forcing horizontal layout seemed sensible at the time since it avoided blank space in the output. The intention was to have sensible defaults to keep configuration options minimal, though that was nearly 4 years ago, and the project has grown with a lot more options. For one, there's the "horizontal" flag (also "-h" in the CLI) which would give the current behaviour for 3 images if it wasn't a special case any more.

You're right to point out how "sensible defaults" aren't going to look sensible to everyone. This would be better handled with more grid configuration options, which is something I've been pondering the last few weeks anyway.

What I'm thinking right now is removing such special cases from the `stitchy-core` crate, and making sure the CLI (`stitchy` crate) can itself apply this logic by passing in exact grid parameters to `stitchy-core`. This would seem better design, and allow users to pass in exact grid parameters in the CLI if they wanted to, while keeping the core crate free of assumptions about how people want it to behave. I'll try to look into this in the next few days.

**Comment by gkuznik** [comment]
Hey @grimace87,
Thanks for explaining, that's totally understandable.
For my and probably most usecases (no complaints over 4 years) this bigger refactoring isn't even needed, simply changing the few lines with the algorithm should suffice to make the grid option behave as expected.
In case you do want more options I'd suggest using Rust's powerful enums by adding a fourth Enum value with the specific sizes like so:
`Fixed(horizontal: u32, vertical: u32) // or mainAxisSize`
You could also modify Horizontal and Vertical to take one parameter each, which would replace the hardcoded 1 for crossAxisSize

**Comment by gkuznik** [comment]
Hey @grimace87,
I just made a small PR, this includes only the change I originally wanted, but if you like I can also take a look at a more customizable option like you proposed.

**Comment by shining-grimace** [comment]
Thanks so much @Friendly-Banana for the contribution! The more I look at it the more I like this solution. I'll give it a proper review in the next 24 hours when I'm home.

I've been procrastinating on this because I've been focused on building an Android app for Stitchy, which should be release within a few days.

Tangential note: my new train if thought is that THIS is the best default behaviour. Whenever I'm using the CLI, I pass "-h" to force horizontal layout even when stitching 2 or 3 images, just because it's easier than stopping to think which edge cases apply in a given situation. And I authored those edge cases.

**Comment by gkuznik** [comment]
Glad I could help, could you release it as a new version on crates.io?
Looking forward to the release of the app, I'm curious to see how you bring Rust to Android.

**Comment by shining-grimace** [comment]
Done! The Stitchy CLI and core crates have been updated, including your change and what I need for the Android app.

The Android app is done, it just needs to be published once I've passed through all of Google Play's hoops. After that, I'll make it a public repo. Hopefully it helps someone integrate Rust into their app; the setup isn't complicated but isn't well-documented either.

**Comment by shining-grimace** [comment]
And now Stitchy is released on the Google Play store! The Android app bundles the current Stitchy core crate with a GUI to select images from the device and configure some of the output parameters.
The repo is now publicly available at https://github.com/grimace87/StitchyMobile.
